name: "Comment check"

on:
  issues:
    types: [opened, edited]
jobs:
  parse_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Check comment and update
        run: |
          echo "Issue number: ${{ github.event.issue.number }}"
          python --version
